version: '2.12.2'

services:
  api:
    image: pta208/dacta-api:1.0.0
    restart: always
    build: 
      dockerfile: Dockerfile
      context: "./api"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_NAME: dacta
    ports:
      - "3001:3001"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: db
    ports: 
      - "3306:3306"
    

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    restart: always
    ports:
      - 8080:8080
